name: bakery_manager_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BakeryManagerFont
      fonts:
        - asset: assets\fonts\RedHatDisplay-Italic-VariableFont_wght.ttf
        - asset: assets\fonts\RedHatDisplay-VariableFont_wght.ttf
